

title: Docência 
email: lucasrdf@fisica.ufrn.br
description: >- # this means to ignore newlines until "baseurl:"
    Coletânea de aulas e materias de ensino em português produzidos por mim. 
baseurl: "/docencia" # the subpath of your site, e.g. /blog
url: "lucasrdfreitas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  lucasrdfreitas


# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults: 
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lucas Freitas"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
